### 开发环境配置
#debug: true

spring:
  datasource:
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/cf_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接数据库的账号
    username: root
    #  连接数据库的密码
    password: wyx
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: axiangcoding@foxmail.com
    password: uqjuaxkpcfzgdgbi


logging:
  config: classpath:conf/logback-dev-spring.xml

cf:
  config:
    # 权限拦截器
    authInterceptor:
      enable: true
    # jwt相关配置
    jwt:
      # jwt默认过期时间为 1000*60*60*8 毫秒
      expireTime: 28800000
      tokenSecret: tokentoken
    # 控制器日志
    controllerLog:
      enable: true
    # 异常处理器日志
    handlerLog:
      enable: true
    # 线程池配置
    threadPool:
      corePoolSize: 10
      maxPoolSize: 100
      queueCapacity: 200
    # swagger配置
    swagger:
      enable: true
    # druid配置
    druid:
      name: admin
      pwd: admin
    # VJ相关配置
    vj:
      user:
        username: axiangcoding
        password: wuyuxiang
      problemListUrl: https://vjudge.net/problem/data
      remoteOJsUrl: https://vjudge.net/util/remoteOJs
      problemHtmlUrl: https://vjudge.net/problem/%s
      checkLoginStatusUrl: https://vjudge.net/user/checkLogInStatus
      doLoginUrl: https://vjudge.net/user/login
    local:
      localJudgePath: http://192.168.122.129:8100
    tempFilePath: D://testfile/
    filePath: D://testfile/
    picturePath: D://testfile/pic/