### 开发环境配置
#debug: true

spring:
  datasource:
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/cf_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接数据库的账号
    username: root
    #  连接数据库的密码
    password: wyx
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: axiangcoding
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: axiangcoding@foxmail.com
    password: uqjuaxkpcfzgdgbi

logging:
  config: classpath:conf/logback-dev-spring.xml

cf:
  config:
    # 权限拦截器
    authInterceptor:
      enable: true
    # jwt相关配置
    jwt:
      # jwt默认过期时间为 1000*60*60*8 毫秒
      expireTime: 28800000
      tokenSecret: axiangcoding
    # 控制器日志
    controllerLog:
      enable: true
    # 异常处理器日志
    handlerLog:
      enable: true
    # 拦截器日志
    interceptorLog:
      enable: true
    # 线程池配置
    threadPool:
      corePoolSize: 10
      maxPoolSize: 20
      queueCapacity: 200
    # swagger配置
    swagger:
      enable: true
    # druid配置
    druid:
      name: admin
      pwd: admin
    file:
      globalPath: D://testfile/
      tempPath: D://testfile/temp/
      picPath: D://testfile/pic/
      avatarPath: D://testfile/avatar/
    local:
      localJudgePath: http://192.168.122.129:8100
      simFilePath: D://testfile/python/
      spiderProjectPath: D://A-阿翔/项目工程/毕设-网上编程题爬取系统/CodingFirstSpider/
      pythonPath: D://Anaconda3/envs/web/python.exe
    spider:
      daemonStatusUrl: http://127.0.0.1:6800/daemonstatus.json
      listProjectsUrl: http://127.0.0.1:6800/listprojects.json
      listSpidersUrl: http://127.0.0.1:6800/listspiders.json?project=%s
      listJobsUrl: http://127.0.0.1:6800/listjobs.json?project=%s
      scheduleUrl: http://127.0.0.1:6800/schedule.json
      logUrl: http://127.0.0.1:6800/logs/%s/%s/%s.log