### 开发环境配置
#debug: true

spring:
  datasource:
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/coding_first?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接数据库的账号
    username: root
    #  连接数据库的密码
    password: mysql
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: axiangcoding@foxmail.com
    password: uqjuaxkpcfzgdgbi

logging:
  config: classpath:conf/logback-dev-spring.xml

cf:
  config:
    # 权限拦截器
    authInterceptor:
      enable: true
    # jwt相关配置
    jwt:
      # jwt默认过期时间为 1000*60*60*8 毫秒
      expireTime: 28800000
      tokenSecret: axiangcoding
    # 控制器日志
    controllerLog:
      enable: true
    # 异常处理器日志
    handlerLog:
      enable: true
    # 拦截器日志
    interceptorLog:
      enable: true
    # 线程池配置
    threadPool:
      corePoolSize: 10
      maxPoolSize: 100
      queueCapacity: 200
    # swagger配置
    swagger:
      enable: true
    # druid配置
    druid:
      name: admin
      pwd: admin
    local:
      localJudgePath: http://192.168.122.129:8100
    file:
      globalPath: D://testfile/
      tempPath: D://testfile/temp/
      picPath: D://testfile/pic/
      avatarPath: D://testfile/avatar/